var1 = open("thefile.txt","r")
print(var1.tell())
var2 = var1.readline()
print(var2)
print(var1.tell())
var3 = (var1.readline())
print(var3)
print(var1.tell())
var4 = var1.readline()
print(var4)
print(var1.tell())
var5 = var1.readline()
print(var5)
var1.close()